search_api_page.search_api_page.*:
  type: config_entity
  label: 'Search page config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    path:
      type: string
      label: 'Path'
    index:
      type: string
      label: 'Search index'
    uuid:
      type: string
